name: coreml-converter
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==2.7.13
    - pip:
        - coremltools==0.3.0
        - keras==1.2.2
        - tensorflow==1
        - scikit-learn==0.15
        - tqdm
        - matplotlib
        - h5py

